name: Sanity test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
      

jobs:
  test_model:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - uses: iterative/setup-cml@v2

    - name: Authenticate to Google Cloud & Pull DVC data
      env:
        GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
      run: |
        echo "$GCP_CREDENTIALS_JSON" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud auth list
        dvc pull model.keras.dvc
        dvc pull samples.dvc

    - name: Run unit tests
      run: |
        python -m test 2>&1 | tee test_output.txt

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "### Test Output" > report.md
        echo "\`\`\`" >> report.md
        cat test_output.txt >> report.md
        echo "\`\`\`" >> report.md
        echo "### Metrics from training" >> report.md
        if [ -f metrics.csv ]; then cat metrics.csv >> report.md; fi
        cml comment create --publish report.md
